version: '2.2'

services:

  postgres:
    container_name: postgres
    image: postgres:13
    volumes:
      - ./Arquivos/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: datawarehouse
    ports:
      - 5432:5432

  etl:
    container_name: python
    volumes:
      - ./Python/ETL:/scripts
      - ./Dados:/dados
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres